name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Check for Gradle files
      run: |
        if [ ! -f build.gradle ] || [ ! -f settings.gradle ]; then
          echo "Gradle configuration files are missing."
          exit 1
        fi

    - name: Generate gradlew if missing
      run: |
        if [ ! -f gradlew ]; then
          gradle wrapper
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add gradlew gradlew.bat gradle/wrapper
          git commit -m "Add Gradle wrapper"
          git push
        fi

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build
